// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dist2
NumericMatrix dist2(NumericMatrix x, NumericMatrix c);
RcppExport SEXP _tddtw_dist2(SEXP xSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(dist2(x, c));
    return rcpp_result_gen;
END_RCPP
}
// dpcore
List dpcore(NumericMatrix M, NumericMatrix C);
RcppExport SEXP _tddtw_dpcore(SEXP MSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type M(MSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type C(CSEXP);
    rcpp_result_gen = Rcpp::wrap(dpcore(M, C));
    return rcpp_result_gen;
END_RCPP
}
// dpcore_window
List dpcore_window(NumericMatrix M, NumericMatrix C, Nullable<NumericVector> ws);
RcppExport SEXP _tddtw_dpcore_window(SEXP MSEXP, SEXP CSEXP, SEXP wsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type M(MSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type C(CSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type ws(wsSEXP);
    rcpp_result_gen = Rcpp::wrap(dpcore_window(M, C, ws));
    return rcpp_result_gen;
END_RCPP
}
// fwt1step
List fwt1step(NumericVector s, NumericVector h, NumericVector g);
RcppExport SEXP _tddtw_fwt1step(SEXP sSEXP, SEXP hSEXP, SEXP gSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type h(hSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type g(gSEXP);
    rcpp_result_gen = Rcpp::wrap(fwt1step(s, h, g));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _tddtw_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tddtw_dist2", (DL_FUNC) &_tddtw_dist2, 2},
    {"_tddtw_dpcore", (DL_FUNC) &_tddtw_dpcore, 2},
    {"_tddtw_dpcore_window", (DL_FUNC) &_tddtw_dpcore_window, 3},
    {"_tddtw_fwt1step", (DL_FUNC) &_tddtw_fwt1step, 3},
    {"_tddtw_rcpp_hello_world", (DL_FUNC) &_tddtw_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_tddtw(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
