# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dist2 <- function(x, c) {
    .Call(`_tddtw_dist2`, x, c)
}

dpcore <- function(M, C) {
    .Call(`_tddtw_dpcore`, M, C)
}

dpcore_window <- function(M, C, ws = NULL) {
    .Call(`_tddtw_dpcore_window`, M, C, ws)
}

fwt1step <- function(s, h, g) {
    .Call(`_tddtw_fwt1step`, s, h, g)
}

rcpp_hello_world <- function() {
    .Call(`_tddtw_rcpp_hello_world`)
}

